MainThreadPeriod: 0.001
Kp: 30
Kd: 0.5
NonZeroAngle: 50
TorCmdValue: 2
InerpolateTime: 10
TorExecTime: 10
net_card: enp3s0
remote_port: /dev/remote
remote_baudrate: 115200
loop_frequency: 500
cycle_time_error_threshold: 0.002
thread_priority: 95
node_motor_num: [4, 4, 5, 5]
motor_max_torque: [10, 90, 150, 70]
motor_min_torque: [-10, -90, -150, -70]

motor_max_current: [10, 60, 70, 30]
motor_min_current: [-10, -60, -70, -30]

motor_max_velocity: [20, 18, 18, 18]
motor_min_velocity: [-20, -18, -18, -18]
right_arm_motor_type: [0, 0, 0, 0]
left_arm_motor_type: [0, 0, 0, 0]
right_leg_motor_type: [1, 1, 2, 2, 3]
left_leg_motor_type: [1, 1, 2, 2, 3]
right_leg_motor_dir: [1, 1, 1, 1, 1]
left_leg_motor_dir: [1, 1, 1, 1, 1]
right_arm_motor_dir: [1, 1, 1, 1]
left_arm_motor_dir: [1, 1, 1, 1]

